#instagram
instagram:
  provider_name: Instagram
  provider_url: https://instagram.com
  endpoints:
    url: https://graph.facebook.com/v10.0/instagram_oembed

#twitter
twitter:
  provider_name: Twitter
  provider_url: http://www.twitter.com/
  endpoints:
    url: https://publish.twitter.com/oembed


#vimeo
vimeo:
  provider_name: Vimeo
  provider_url: https://vimeo.com/
  endpoints:
    url: https://vimeo.com/api/oembed.json


#youtube
youtube:
  provider_name: YouTube
  provider_url: https://www.youtube.com/
  endpoints:
    url: https://www.youtube.com/oembed

# Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
spring:
  http:
    encoding:
      - charset: UTF-8
        enabled: true
        force: true